### ISSUE TITLE
New version (2) requires 1 migrations more than what you have.

### ISSUE THREAD

**Issue by robinbonnes** [flutterings/sqflite_migration#1]
Thanks for this great plugin.

However, when I migrate it says: 

`Failed assertion: line 27 pos 12: 'config.migrationScripts.length >= newVersion': New version (2) requires 1 migrations more than what you have.`

Also it gives a non-fatal error when you start with an empty migration array.

**Comment by esarbanis** [comment]
Hi @robinbonnes and thank you for trying out sqflite_migration!

It would be great if you could provide the output of `flutter doctor` and maybe a test case. It would greatly improve the time needed to debug and fix this.

If you have already spotted a possible fix feel free to create a PR 😃

**Comment by jamesncl** [comment]
I've also encountered this problem. I think the steps to reproduce are as follows - this is just what I have done. Sorry I don't have time to investigate furhter, I'm massively under pressure to code my ass off at the moment.
- I had to do the initial create database without using the plugin, because it threw an error if the migration scripts argument was empty (annoying!)
- Then, a week later, I added the initial create database script (that I already used to create the database) plus 2 migration scripts, and changed by database init code to use the plugin. because now I have migrations to manage
- This is when I get the error. I think it's getting confused somehow because it didn't create the database initially... I have no idea. It's very confusing!

Thanks for the great plugin, definitely fulfulls an unmet need in flutter!

**Comment by jamesncl** [comment]
I've just implemented the logic manually as described in [your article here](https://medium.com/flutter-community/migrating-a-mobile-database-in-flutter-sqlite-44ac618e4897). I got the same problem using this code:

```
onUpgrade: (Database db, int oldVersion, int newVersion) async {
    for (var i = oldVersion - 1; i <= newVersion - 1; i++) {
      await db.execute(migrationScripts[i]);
    }  
  }
```

Is there a mistake - shouldn't it be while `i < newVersion - 1` in the for loop? When I use that, it works.

**Comment by esarbanis** [comment]
@jamesncl can you try with the newest version of the library?

**Comment by marcelovbcfilho** [comment]
I have the same issue, I have an List<String> migatrion with 3 of lenght, when opening the database with openDatabaseWithMigration, inside your code there is a "version: config.migrationScripts.length + 1,", and inside the Migrator you have an assert "assert(config.migrationScripts.length >= newVersion,", so how my migration list that has only 3 of lenght will be run if the new version is 4 ???

**Comment by esarbanis** [comment]
Hi @marcelovbcfilho there is an implicit assertion that in version 1 there are no`migrationScripts` but rather only `initializationScript`. This means that the version of the database is always the number of `migrationScripts` + the initialization script. So `config.migrationScripts.length + 1` holds this logic.

**Comment by zoref** [comment]
I have the same problem. It fails on this assert `assert(config.migrationScripts.length >= newVersion,
        'New version ($newVersion) requires ${newVersion - config.migrationScripts.length} migrations more than what you have.');` in `executeMigration`.

Shouldn't that be `config.migrationScripts.length >= newVersion - 1` since the version is `config.migrationScripts.length + 1` ?

I believe @jamesncl is right about the for loop condition as well.

**Comment by Tibasa** [comment]
Same problem! Any solution?

**Comment by Dimitry82** [comment]
Correct will be like this in migrator.dart:

`  Future<void> executeMigration(Database db, int oldVersion, int newVersion) async {
    assert(oldVersion < newVersion, 'The newVersion($newVersion) should always be greater than the oldVersion($oldVersion).');
    assert(config.migrationScripts.length <= newVersion, 'New version ($newVersion) requires ${newVersion - config.migrationScripts.length} migrations more than what you have.');

    for (var i = oldVersion - 1; i < newVersion - 1; i++) {
      await db.execute(config.migrationScripts[i]);
    }
  }`

**Comment by rodyfernandez** [comment]
con mi amigo Matias Araus lo resolvimos de la siguiente forma:

```
final migrationScripts = [
  'CREATE TABLE Cuotas ('
      ' idcuota INTEGER PRIMARY KEY, '
      ' creditoid INTEGER, '
      ' descripcion TEXT, '
      ' importecuota REAL, '
      ' codigo INTEGER, '
      ' razonsocial TEXT, '
      ' direccion TEXT, '
      ' importepagado REAL, '
      ' localidad TEXT, '
      ' tipocuota TEXT '
      ')',
   'update cuotas set importecuota = importecuota + 2 ',
   'update cuotas set importecuota = importecuota + 3',
   'update cuotas set importecuota = importecuota + 4',
   'update cuotas set importecuota = importecuota + 5 ',
   'update cuotas set importecuota = importecuota + 6 ',

         
];

```

```
  initDB() async {
    Directory documentDirectory = await getApplicationDocumentsDirectory();

    final path = join(documentDirectory.path, 'database12.db');
    return await openDatabase(path, version: migrationScripts.length  ,
        onCreate: (Database db, int version) async {
      migrationScripts.forEach((script) async => await db.execute(script));
    }, onUpgrade: (Database db, int oldVersion, int newVersion) async {
    
      for (var i = oldVersion  ; i < newVersion ; i++) {

       
        await db.execute(migrationScripts[i]);

      }

    });
  }
```

Con una sola lista, ya que el create solo ingresa por unica vez al crear el archivo, y esa primera vez el onUpgrade no se ejecuta porque oldversion no existe aun.

**Comment by icanall10** [comment]
Working example
https://github.com/icanall10/test/blob/master/flutter_sqlite_migrations.dart

**Comment by Tomucha** [comment]
Same issue. For now I'm using dependency as:

       git: https://github.com/DrLabx/sqflite_migration/

Thanks for that.

But as @marcelovbcfilho pointed out 9 months ago - this simply cannot work correctly ever. Please merge the pull request and release a new version.

**Comment by ghost** [comment]
> Same issue. For now I'm using dependency as:
> 
> ```
>    git: https://github.com/DrLabx/sqflite_migration/
> ```
> 
> Thanks for that.
> 
> But as @marcelovbcfilho pointed out 9 months ago - this simply cannot work correctly ever. Please merge the pull request and release a new version.

You're welcome! I've sent an email to the maintainer, but haven't had any response yet. Hopefully he'll come to us soon.

**Comment by christianreiser** [comment]
Since there is no response from the owner I created a fork with the pull request from @Rinat-Suleimanov. 
You can use this version by changing the dependencies in pubspec.yaml to:
```
dependencies:
    sqflite_migration:
        git:
          url: https://github.com/christianreiser/sqflite_migration
```

Let me know if there is a better way to fix it.

**Comment by esarbanis** [comment]
Sorry for leaving this hanging for so long ... I had some personal and professional issues to sort out. I will dig deeper into this issue and will get back ASAP.
