### ISSUE TITLE
requires migrationScripts to  have a query

### ISSUE THREAD

**Issue by MrMoronIV** [flutterings/sqflite_migration#2]
Can this be made so the migrationScripts can just receive an empty List? Or an empty string in the list as the query?

It now assumes there's already a migration required but I was thinking ahead of possible required database changes in the future and now I need to provide a migration query like `select 1`

**Comment by esarbanis** [comment]
Hi @MrMoronIV ,

I think you have a valid point. We should be able to tolerate empty `migrationScripts`

**Comment by esarbanis** [comment]
Hm ... I have checked the code and we actually tolerate empty `migrationScripts`, check this [test case](https://github.com/flutterings/sqflite_migration/blob/master/test/src/migrator_test.dart#L13) to see how.

**Comment by MrMoronIV** [comment]
How would you define the script then? As `null` or `[]` or `['']`?

**Comment by esarbanis** [comment]
According to the test case I mentioned above the `MigrationConfig` should have `[]` both in `initializationScript` and in `migrationScripts`.

Isn't the above behavior acceptable?

**Comment by esarbanis** [comment]
OK, I now understand what is going on. I had put assertions in the `MigrationConfig` constructor and then I mocked it in the tests ... 🙄 .

I had the tests in place to allow the behavior you mentioned, but I was mocking `MigrationConfig` and thus its constructor was never called. So, I had passing tests that should have failed ...

I will remove the `isEmpty` assertions from `MigrationConfig` as well as the mock in the tests. Will release soon.

**Comment by esarbanis** [comment]
Issue fixed in v0.1.2

**Comment by MrMoronIV** [comment]
Thank you, I'm glad I wasn't going insane despite my name :p

So putting `[]` as the migrationscript now works?

On another note but maybe unrelated, is there a way to reset the database so it gets recreated during testing or is that happening automatically when the app is built from scratch again (not just restarting)?

And secondly, am I correct if there is no way to inspect a database as if there was some sort of phpmyadmin?

**Comment by esarbanis** [comment]
Yes, putting `[]` in `migrationScripts` will work from now own. 

You can use the [`databaseExists`](https://github.com/tekartik/sqflite/blob/master/sqflite/lib/sqflite.dart#L177) and [`databaseDelete`](https://github.com/tekartik/sqflite/blob/master/sqflite/lib/sqflite.dart#L171) methods, before calling `openDatabase`, to always recreate the database.

You can try StackOverflow for your last question, I am not aware of any such tool.

**Comment by MrMoronIV** [comment]
I don't want to spoil your tea but when I use `[]` for the migration script it says:

```
type 'List<dynamic>' is not a subtype of type 'List<String>'
```
My code
```
final migrations = [];

final config = MigrationConfig(
    initializationScript: initialScript, migrationScripts: migrations);
```

It says migrations is of type `List<dynamic>` and `migrationScripts` expects `List<String>`.
My pubspec.yaml `  sqflite_migration: ^0.1.2`

**Comment by esarbanis** [comment]
Try using a correctly typed list like `<String>[]`.
