### ISSUE TITLE
Don't migrate with release version application

### ISSUE THREAD

**Issue by jay-web** [flutterings/sqflite_migration#5]
Hi, we are trying to migrate sqflite database from Cordova based application to flutter based application. We implemented the sqflite_migration package in the flutter application. Now at testing if we install a flutter debug version app on Cordova debug version app, so successfully able to transfer/migrate the data. However, if we try to install on releasing a version of both the app, it won't work. No data get migrated.
Please assist. Thanks in advance !!

**Comment by esarbanis** [comment]
Hi @jay-web and thanks for using the library.

Can you give me a bit more information? I suspect that the production database contains some data, was that the case for the test one as well?

**Comment by jay-web** [comment]
Hi @esarbanis, thank you for your response. Basically, everything is the same in production as well as in a testing database. With the same code, when we run the library on debug apk it worked well but not on production apk. 
Are there any specific code changes or implementation required on the native android side or in the Gradle side.

**Comment by esarbanis** [comment]
Does it silently fail or do you have an error message? It would be a good start 🙂

**Comment by jay-web** [comment]
In log getting the error message, might be specific to the error :

**05-15 12:00:50.863  3063  5222 E SQLiteDatabase:** Error inserting flex_time=0 job_id=-1 period=2000 source=16 requires_charging=0 preferred_network_type=1 target_class=com.google.android.gms.measurement.PackageMeasurementTaskService user_id=0 target_package=com.google.android.gms tag=Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG task_type=0 required_idleness_state=0 service_kind=0 source_version=201516000 persistence_level=1 preferred_charging_state=1 required_network_type=0 runtime=1589524250847 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}} last_runtime=0 from {P:3063;U:10021}

**05-15 12:00:50.863  3063  5222 E SQLiteDatabase:** android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067 SQLITE_CONSTRAINT_UNIQUE)

**Comment by esarbanis** [comment]
I see that there is a unique constraint violated in `pending_ops.tag`, the reason you might not have this error in the test environment could be because of the difference in data, that do not violate this constraint. I don't see any library-specific issue in the error message ... 🤔

**Comment by jay-web** [comment]
Apology, I don't have too much knowledge in this regard. What is **pending_ops.tag** here means? Because as I mentioned all the data are the same in testing as well as in production.

**Comment by esarbanis** [comment]
From what I can derive from the error message there is a unique constraint in  `pending_ops` table, which dictates that the combination of `tag`, `target_class`, `target_package`, `user_id` fields must be unique among all the records of the  `pending_ops` table.

A logical conclusion could be that this unique constraint is not present in the test database, but it is in the production one. But I don't see how this could be related to the library ... 🤔

**Comment by jay-web** [comment]
Hi, I just checked the log of testing environment and getting the same error of unique constraint violated there also. but data has been transferred successfully in this case.

**Comment by jay-web** [comment]
Thanks, @esarbanis , It was just a different issue not related to the library. Thanks for your support and guidance.

**Comment by esarbanis** [comment]
No problem @jay-web . If you like the library it would be awesome if you can give it a star 🙂
